services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=0ffd4c0d93883b0b6ccd295ab193
      - POSTGRES_USER=postgres
      - POSTGRES_DB=axenix
      - TZ=Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - general
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  fastapi:
    build: .
    container_name: fastapi
    environment:
      - SECRET_KEY=c930fcdc49a10a69bfd11b1212c4146a493fef9868c8d0cf67d29bf465dcbf53
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://postgres:123456@postgres/axenix
      - SQLALCHEMY_DATABASE_SYNC_URL=postgresql+psycopg://postgres:123456@postgres/axenix
      - BROKER_URL=redis://redis:6379/0
      - WORKERS=2
      - HOST=0.0.0.0
    ports:
      - "127.0.0.1:8082:8082"
    volumes:
      - logs:/backend/logs
    depends_on:
      - postgres
      - redis
    networks:
      - general

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kfjqeqrwNa4@gmail.com
      PGADMIN_DEFAULT_PASSWORD: kfjqeqrwNa4@gmail.com
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - general


volumes:
  postgres_data:
  redis_data:
  es_data:
  logs:
  promtail_positions:

networks:
  general:
    external: true


