"""init

Revision ID: 2b9a4a7ce5cb
Revises: 5cd9d2419f8e
Create Date: 2025-04-05 14:34:26.961116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9a4a7ce5cb'
down_revision: Union[str, None] = '5cd9d2419f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelves', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelves', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
